In [2]:
import pandas as pd
import numpy as np

In [4]:
df = pd.read_csv('stock_data_total.csv')
df.head(3)

,date,close,change,open,high,low,volume,industry,keyword,ticker,exrate
0,01/06/2025,104000.0,하락 300,104900.0,104900.0,103900.0,235960,바이오,유한양행,100,NaN
1,02/06/2025,104000.0,하락 300,104900.0,104900.0,103900.0,235960,바이오,유한양행,100,NaN
2,03/06/2025,103000.0,"하락 1,000",104400.0,105200.0,102900.0,448823,바이오,유한양행,100,NaN

In [8]:
industry_tickers = df.groupby('industry')['keyword'].unique().reset_index()
industry_tickers.columns = ['industry', 'tickers']
industry_tickers

   industry                                  tickers
0       건설업         [현대건설, GS건설, 삼성물산, 대우건설, 코오롱글로벌]
1     금속제조업           [포스코홀딩스, 고려아연, 현대제철, 풍산, 세아제강]
2       금융업       [KB금융, 하나금융지주, 신한지주, 삼성증권, 우리금융지주]
3       바이오          [유한양행, 삼성바이오, 한미약품, 대웅제약, 셀트리온]
4    반도체제조업     [삼성전자, 에스케이하이닉스, DB하이텍, 엔비디아, 한미반도체]
5       방송업      [CJ ENM, 스튜디오드래곤, 제이콘텐트리, NEW, SBS]
6       보험업     [삼성화재해상보험, 삼성생명, 한화생명, DB손해보험, 현대해상]
7      석유정제      [금호석유화학, LG화학, SK케미칼, 코오롱인더, 한화솔루션]
8       식료품          [cj제일제당, 농심, 오뚜기, spc삼립, 하이트진로]
9       에너지    [SK이노베이션, 한국쉘석유, 한국전력공사, S-Oil, SK가스]
10      자동차             [현대차, 기아, 한국타이어, 테슬라, 현대모비스]
11     전자부품     [엘지디스플레이, 이수페타시스, 엘지전자, LG이노텍, 삼성전기]
12    정보통신업   [KT,  SK텔레콤,  LG유플러스, 현대오토에버, 삼성에스디에스]
13      조선업  [한화오션, 삼성중공업, HMM, 한화에어로스페이스, HD한국조선해양]
14       지수    [코스피, 코스닥, NASDAQ, S&P500, Dow Jones]
15     항공운송     [대한항공, 아시아나항공,  HMM, 현대글로비스, CJ대한통운]
16       환율     [USD/KRW, USD/JPY, EUR/USD, USD/CNY]

In [10]:
filtered_df = industry_tickers[~industry_tickers['industry'].isin(['지수', '환율'])]
filtered_df

   industry                                  tickers
0       건설업         [현대건설, GS건설, 삼성물산, 대우건설, 코오롱글로벌]
1     금속제조업           [포스코홀딩스, 고려아연, 현대제철, 풍산, 세아제강]
2       금융업       [KB금융, 하나금융지주, 신한지주, 삼성증권, 우리금융지주]
3       바이오          [유한양행, 삼성바이오, 한미약품, 대웅제약, 셀트리온]
4    반도체제조업     [삼성전자, 에스케이하이닉스, DB하이텍, 엔비디아, 한미반도체]
5       방송업      [CJ ENM, 스튜디오드래곤, 제이콘텐트리, NEW, SBS]
6       보험업     [삼성화재해상보험, 삼성생명, 한화생명, DB손해보험, 현대해상]
7      석유정제      [금호석유화학, LG화학, SK케미칼, 코오롱인더, 한화솔루션]
8       식료품          [cj제일제당, 농심, 오뚜기, spc삼립, 하이트진로]
9       에너지    [SK이노베이션, 한국쉘석유, 한국전력공사, S-Oil, SK가스]
10      자동차             [현대차, 기아, 한국타이어, 테슬라, 현대모비스]
11     전자부품     [엘지디스플레이, 이수페타시스, 엘지전자, LG이노텍, 삼성전기]
12    정보통신업   [KT,  SK텔레콤,  LG유플러스, 현대오토에버, 삼성에스디에스]
13      조선업  [한화오션, 삼성중공업, HMM, 한화에어로스페이스, HD한국조선해양]
15     항공운송     [대한항공, 아시아나항공,  HMM, 현대글로비스, CJ대한통운]